# Generated by Django 5.0.6 on 2024-07-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_options_remove_comment_dislike_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commentlikedislike',
            name='unique_user_comment_vote',
        ),
        migrations.AlterUniqueTogether(
            name='commentlikedislike',
            unique_together={('user', 'comment')},
        ),
    ]
