# Generated by Django 5.0.6 on 2024-07-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_commentlikedislike_unique_user_comment_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikedislike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_vote', to='posts.comment'),
        ),
    ]
