# Generated by Django 5.0.6 on 2024-07-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_commentlikedislike_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pk',)},
        ),
    ]
