# Generated by Django 5.0.6 on 2024-07-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikedislike',
            name='vote',
            field=models.CharField(blank=True, choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=8, null=True),
        ),
    ]
